// packages/kubernetes-client-svelte/src/routes/login/+page.svelte
<script lang="ts">
  import TokenInput from './TokenInput.svelte'

  let initialValue: string = '' // localStorage.getItem('kubetoken') ?? ''
  let alerts: string[] = []

  function removeAlert(index: number): void {
    alerts.splice(index, 1)
    console.debug('removed alert', index)
  }

  function addAlert(message: string, timeout?: number): void {
    const len = alerts.push(message)
    console.debug('added alert', len - 1)
    if (timeout) {
      setTimeout(() => removeAlert(len - 1), timeout)
    }
  }

  function setToken(token: string): void {
    console.log('got token', token)
  }
</script>

<h1>Login to Kubernetes</h1>
<div id="alerts">
  {#each alerts as alert, i}
    <div role="alert" class="alert alert-danger fade show d-flex align-items-center justify-content-between">
      <span>{alert}</span>
      <button type="button" class="btn-close" on:click={() => removeAlert(i)} />
    </div>
  {/each}
</div>
<div class="row mt-5 mb-5">
  <div class="col">
    <TokenInput />
  </div>
</div>

// packages/kubernetes-client-angular/projects/kubernetes-client-example-angular/src/app/login/login.component.ts
import { Component } from '@angular/core'
import { SelfSubjectRulesReviewService } from '../store/self-subject-rules-review.service'
import { KubernetesAuthorizerService } from '../../../../kubernetes-client-angular/src/lib/kubernetes-authorizer.service'

@Component({
  selector: 'app-page',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent {
  initialValue: string
  alerts: string[] = []

  constructor(private authorizer: KubernetesAuthorizerService, private ssrrService: SelfSubjectRulesReviewService) {
    this.initialValue = localStorage.getItem('kubetoken') ?? ''
  }

  setToken(token: string): void {
    this.authorizer.setToken(token)
    console.log('got token', token)
    this.ssrrService
      .add({
        apiVersion: 'authorization.k8s.io/v1',
        kind: 'SelfSubjectRulesReview',
        spec: {
          namespace: 'default',
        },
      })
      .subscribe({
        next: (value) => {
          console.log('result', value)
          localStorage.setItem('kubetoken', token)
        },
        error: (err) => {
          console.warn('error!', err)
          this.addAlert(err.message)
          localStorage.removeItem('kubetoken')
        },
      })
  }

  addAlert(message: string, timeout?: number): void {
    const len = this.alerts.push(message)
    console.debug('added alert', len - 1)
    if (timeout) {
      setTimeout(() => this.removeAlert(len - 1), timeout)
    }
  }

  removeAlert(index: number): void {
    this.alerts.splice(index, 1)
    console.debug('removed alert', index)
  }
}

<h1 class="mb-5">Login to Kubernetes</h1>
<div id="alerts">
  <div
    role="alert"
    *ngFor="let alert of alerts; index as i"
    class="alert alert-danger fade show d-flex align-items-center justify-content-between"
  >
    <span>{{ alert }}</span>
    <button
      type="button"
      class="btn-close"
      (click)="removeAlert(i)">
    </button>
  </div>
</div>
<div class="row mt-5 mb-5">
  <div class="col">
    <app-token-input (tokenEvent)="setToken($event)" [initialValue]="initialValue" />
  </div>
</div>
