// packages/kubernetes-client-angular/projects/kubernetes-client-example-angular/src/app/login/token-input/token-input.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, OnInit, Output } from '@angular/core'
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms'
import { JwtValidator } from '../../validators/jwt-validator'

@Component({
  standalone: true,
  selector: 'app-token-input',
  imports: [ReactiveFormsModule],
  templateUrl: './token-input.component.html',
  styleUrls: ['./token-input.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TokenInputComponent implements OnInit {
  @Output()
  tokenEvent = new EventEmitter<string>()

  tokenControl = new FormControl('', { nonNullable: true, validators: [Validators.required, JwtValidator()] })
  tokenClass = ''

  buttonClick(): void {
    if (this.tokenControl.valid) {
      this.tokenEvent.emit(this.tokenControl.value)
    }
  }

  ngOnInit(): void {
    this.tokenControl.valueChanges.subscribe(() => {
      if (this.tokenControl.valid) {
        this.tokenClass = 'is-valid'
      } else {
        this.tokenClass = 'is-invalid'
      }
    })
  }
}

<div class="input-group has-validation">
  <label class="visually-hidden" for="token">Token</label>
  <input
    id="token"
    class="form-control"
    [class]="tokenClass"
    type="password"
    placeholder="Token"
    [formControl]="tokenControl"
  />
  <button
    type="button"
    class="btn btn-primary"
    id="btnSubmit"
    (click)="buttonClick()"
    [disabled]="tokenControl.invalid"
  >
    Create Client
  </button>
  <div class="invalid-feedback">Please provide a valid Kubernetes token</div>
</div>

// packages/kubernetes-client-svelte/src/routes/login/TokenInput.svelte
<script lang="ts">
  import { z } from 'zod'
  import { superForm } from 'sveltekit-superforms/client'
  export let token: string = ''
  let tokenClass = ''

  function buttonClick(): void {
    token = $form.token
  }

  const schema = z.object({
    token: z.string().min(2),
  })

  const { form, errors, enhance } = superForm(schema, {
    SPA: true,
    validators: {
      token: (value) => (value.length < 3 ? 'asdfl' : null),
    },
  })
</script>

<form use:enhance>
  <div class="input-group has-validation">
    <label class="visually-hidden" for="token">Token</label>
    <input id="token" class="form-control {tokenClass}" type="password" placeholder="Token" bind:value={$form.token} />
    <button type="button" class="btn btn-primary" id="btnSubmit" on:click={buttonClick}> Create Client </button>
    <div class="invalid-feedback">Please provide a valid Kubernetes token</div>
  </div>
</form>
